/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICommitmentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getUserCommitments"
      | "isNullifierUsed"
      | "isValidCommitment"
      | "nullifyCommitment"
      | "registerCommitment"
      | "updateCommitment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CommitmentNullified" | "CommitmentRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getUserCommitments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isNullifierUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidCommitment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nullifyCommitment",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCommitment",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCommitment",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getUserCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nullifyCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCommitment",
    data: BytesLike
  ): Result;
}

export namespace CommitmentNullifiedEvent {
  export type InputTuple = [
    user: AddressLike,
    commitment: BytesLike,
    nullifier: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    commitment: string,
    nullifier: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    commitment: string;
    nullifier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitmentRegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    commitment: BytesLike,
    commitmentType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    commitment: string,
    commitmentType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    commitment: string;
    commitmentType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ICommitmentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ICommitmentRegistry;
  waitForDeployment(): Promise<this>;

  interface: ICommitmentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getUserCommitments: TypedContractMethod<
    [user: AddressLike],
    [
      [string, string] & {
        collateralCommitment: string;
        debtCommitment: string;
      }
    ],
    "view"
  >;

  isNullifierUsed: TypedContractMethod<
    [nullifier: BytesLike],
    [boolean],
    "view"
  >;

  isValidCommitment: TypedContractMethod<
    [commitment: BytesLike],
    [boolean],
    "view"
  >;

  nullifyCommitment: TypedContractMethod<
    [commitment: BytesLike, nullifier: BytesLike],
    [void],
    "nonpayable"
  >;

  registerCommitment: TypedContractMethod<
    [commitment: BytesLike, commitmentType: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCommitment: TypedContractMethod<
    [oldCommitment: BytesLike, newCommitment: BytesLike, nullifier: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getUserCommitments"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, string] & {
        collateralCommitment: string;
        debtCommitment: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isNullifierUsed"
  ): TypedContractMethod<[nullifier: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidCommitment"
  ): TypedContractMethod<[commitment: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nullifyCommitment"
  ): TypedContractMethod<
    [commitment: BytesLike, nullifier: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerCommitment"
  ): TypedContractMethod<
    [commitment: BytesLike, commitmentType: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCommitment"
  ): TypedContractMethod<
    [oldCommitment: BytesLike, newCommitment: BytesLike, nullifier: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CommitmentNullified"
  ): TypedContractEvent<
    CommitmentNullifiedEvent.InputTuple,
    CommitmentNullifiedEvent.OutputTuple,
    CommitmentNullifiedEvent.OutputObject
  >;
  getEvent(
    key: "CommitmentRegistered"
  ): TypedContractEvent<
    CommitmentRegisteredEvent.InputTuple,
    CommitmentRegisteredEvent.OutputTuple,
    CommitmentRegisteredEvent.OutputObject
  >;

  filters: {
    "CommitmentNullified(address,bytes32,bytes32,uint256)": TypedContractEvent<
      CommitmentNullifiedEvent.InputTuple,
      CommitmentNullifiedEvent.OutputTuple,
      CommitmentNullifiedEvent.OutputObject
    >;
    CommitmentNullified: TypedContractEvent<
      CommitmentNullifiedEvent.InputTuple,
      CommitmentNullifiedEvent.OutputTuple,
      CommitmentNullifiedEvent.OutputObject
    >;

    "CommitmentRegistered(address,bytes32,uint8,uint256)": TypedContractEvent<
      CommitmentRegisteredEvent.InputTuple,
      CommitmentRegisteredEvent.OutputTuple,
      CommitmentRegisteredEvent.OutputObject
    >;
    CommitmentRegistered: TypedContractEvent<
      CommitmentRegisteredEvent.InputTuple,
      CommitmentRegisteredEvent.OutputTuple,
      CommitmentRegisteredEvent.OutputObject
    >;
  };
}
