/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZKVerifier,
  IZKVerifierInterface,
} from "../../../src/interfaces/IZKVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "enum IZKVerifier.ProofType",
        name: "proofType",
        type: "uint8",
      },
    ],
    name: "getVerificationKeyHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum IZKVerifier.ProofType",
        name: "proofType",
        type: "uint8",
      },
      {
        components: [
          {
            internalType: "uint256[2]",
            name: "a",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[2][2]",
            name: "b",
            type: "uint256[2][2]",
          },
          {
            internalType: "uint256[2]",
            name: "c",
            type: "uint256[2]",
          },
        ],
        internalType: "struct IZKVerifier.Proof",
        name: "proof",
        type: "tuple",
      },
      {
        internalType: "uint256[]",
        name: "publicInputs",
        type: "uint256[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZKVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IZKVerifierInterface {
    return new Interface(_abi) as IZKVerifierInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IZKVerifier {
    return new Contract(address, _abi, runner) as unknown as IZKVerifier;
  }
}
