/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CommitmentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedCallers"
      | "collateralCommitments"
      | "commitmentExists"
      | "commitmentOwner"
      | "commitmentTypes"
      | "debtCommitments"
      | "getCommitmentOwner"
      | "getCommitmentType"
      | "getUserCommitments"
      | "isNullifierUsed"
      | "isValidCommitment"
      | "nullifiers"
      | "nullifyCommitment"
      | "owner"
      | "registerCommitment"
      | "renounceOwnership"
      | "setAuthorizedCaller"
      | "transferOwnership"
      | "updateCommitment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommitmentNullified"
      | "CommitmentRegistered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralCommitments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitmentExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitmentOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitmentTypes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "debtCommitments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitmentOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitmentType",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCommitments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isNullifierUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidCommitment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nullifiers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nullifyCommitment",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerCommitment",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCaller",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCommitment",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitmentExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitmentOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitmentTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debtCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitmentOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitmentType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nullifiers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nullifyCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCommitment",
    data: BytesLike
  ): Result;
}

export namespace CommitmentNullifiedEvent {
  export type InputTuple = [
    user: AddressLike,
    commitment: BytesLike,
    nullifier: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    commitment: string,
    nullifier: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    commitment: string;
    nullifier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitmentRegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    commitment: BytesLike,
    commitmentType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    commitment: string,
    commitmentType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    commitment: string;
    commitmentType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CommitmentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CommitmentRegistry;
  waitForDeployment(): Promise<this>;

  interface: CommitmentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  collateralCommitments: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  commitmentExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  commitmentOwner: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  commitmentTypes: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  debtCommitments: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getCommitmentOwner: TypedContractMethod<
    [commitment: BytesLike],
    [string],
    "view"
  >;

  getCommitmentType: TypedContractMethod<
    [commitment: BytesLike],
    [bigint],
    "view"
  >;

  getUserCommitments: TypedContractMethod<
    [user: AddressLike],
    [
      [string, string] & {
        collateralCommitment: string;
        debtCommitment: string;
      }
    ],
    "view"
  >;

  isNullifierUsed: TypedContractMethod<
    [nullifier: BytesLike],
    [boolean],
    "view"
  >;

  isValidCommitment: TypedContractMethod<
    [commitment: BytesLike],
    [boolean],
    "view"
  >;

  nullifiers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  nullifyCommitment: TypedContractMethod<
    [commitment: BytesLike, nullifier: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerCommitment: TypedContractMethod<
    [commitment: BytesLike, commitmentType: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCommitment: TypedContractMethod<
    [oldCommitment: BytesLike, newCommitment: BytesLike, nullifier: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "collateralCommitments"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "commitmentExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "commitmentOwner"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "commitmentTypes"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "debtCommitments"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getCommitmentOwner"
  ): TypedContractMethod<[commitment: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getCommitmentType"
  ): TypedContractMethod<[commitment: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserCommitments"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, string] & {
        collateralCommitment: string;
        debtCommitment: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isNullifierUsed"
  ): TypedContractMethod<[nullifier: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidCommitment"
  ): TypedContractMethod<[commitment: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nullifiers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nullifyCommitment"
  ): TypedContractMethod<
    [commitment: BytesLike, nullifier: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerCommitment"
  ): TypedContractMethod<
    [commitment: BytesLike, commitmentType: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedCaller"
  ): TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCommitment"
  ): TypedContractMethod<
    [oldCommitment: BytesLike, newCommitment: BytesLike, nullifier: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CommitmentNullified"
  ): TypedContractEvent<
    CommitmentNullifiedEvent.InputTuple,
    CommitmentNullifiedEvent.OutputTuple,
    CommitmentNullifiedEvent.OutputObject
  >;
  getEvent(
    key: "CommitmentRegistered"
  ): TypedContractEvent<
    CommitmentRegisteredEvent.InputTuple,
    CommitmentRegisteredEvent.OutputTuple,
    CommitmentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CommitmentNullified(address,bytes32,bytes32,uint256)": TypedContractEvent<
      CommitmentNullifiedEvent.InputTuple,
      CommitmentNullifiedEvent.OutputTuple,
      CommitmentNullifiedEvent.OutputObject
    >;
    CommitmentNullified: TypedContractEvent<
      CommitmentNullifiedEvent.InputTuple,
      CommitmentNullifiedEvent.OutputTuple,
      CommitmentNullifiedEvent.OutputObject
    >;

    "CommitmentRegistered(address,bytes32,uint8,uint256)": TypedContractEvent<
      CommitmentRegisteredEvent.InputTuple,
      CommitmentRegisteredEvent.OutputTuple,
      CommitmentRegisteredEvent.OutputObject
    >;
    CommitmentRegistered: TypedContractEvent<
      CommitmentRegisteredEvent.InputTuple,
      CommitmentRegisteredEvent.OutputTuple,
      CommitmentRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
